POST http://localhost:8080/api/admin/item
Content-Type: application/json
token: 65a5edd0d5378860cf637840

{
  "name": "ręka",
  "price": 1,
  "properties" : "ścieżka prowadzi lewą",
  "inStack" : 10
}