POST http://localhost:8080/api/admin/item
Content-Type: application/json
token: 65a7b55d06261860f0f2d242

{
  "name": "co jest nie tak",
  "price": 43,
  "properties" : "co bardzo",
  "inStack" : 69
}