POST http://localhost:8080/api/order
content-type: application/json
token: 65a7fb1dc4ac25ee0b6ea492

{
  "productInfo" : [
    {
      "productID" : "65a7c85448d86ffc5df67fdb",
      "amount" : 40
    }
  ]
}

