POST http://localhost:8080/api/admin/user
Content-Type: application/json
token: 65a7d946a7bd09f1ae929101

{
  "nick": "faasd fasdf vasdfjnie123",
  "password": "bardzo",
  "mail" : "og?",
  "admin" : true
}